### ISSUE TITLE
RaspberryPi buster as of 2020-12-02 "No autostart"

### ISSUE THREAD

**Issue by volkerwarnecke** [rudiratlos/hotspot#23]
Hello Rudi,
thanks for all your effort to create this. 
I used it for creating educational hotspots with RaspiZero in TOGO, Africa, with content from worldpossible.org.

With latest update/upgrade, I lost the autostart function.
Long searches reveal, what retrospectivly is really obivous in your code,  the solution
.
In the /usr/local/sbin/hotspot file... in the section where it deals with "rc.local"...  
root@raspi#hotspot modpar self autostart 
hotspot  enters a line into rc.local.

hotspot startmode try >>/tmp/hotspot.log 2>&1
Results in this: 
                 hotspot startmode try... .
It didn't autostart with this. 

I commented it... but it didn't autostart either.
                #hotspot startmode try >>/tmp/hotspot.log 2>&1

After i put, in this line of code, (just and lonley):

                  hotspot start >>/tmp/hotspot.log 2>&1

everything worked fine.

Best regards
Volker Warnecke

P.S.:
if you may need one day "CISCO Networking ONline training"  (www.netacad.com) for free...let me know.
I'm instructor trainer with this, and do have the right to onboard intressees. ;)

**Comment by rudiratlos** [comment]
Hello Volker,

you should use:
hotspot modpar self autostart yes

you've ommited 'yes', this will set the script variable to an empty value.

hotspot will autostart if the variable autostart="yes"

the required entry in rc.local is:

hotspot startmode try >>/tmp/hotspot.log 2>&1

**Comment by ScruffR** [comment]
@rudiratlos,

I'm running into a similar issue but I have double checked that I used `hotspot modpar self autostart yes` but it still doesn't start as expected
The syslog shows this
```
root@raspberrypi:~# hotspot syslog
Feb 16 17:17:25 raspberrypi systemd[1]: Starting hotspot...
Feb 16 17:17:29 raspberrypi hotspot[374]: trying    hotspot
Feb 16 17:17:30 raspberrypi hotspot[374]:   DHCP    wait for IPadr on wlan0
Feb 16 17:17:32 raspberrypi hotspot[374]:   DHCP    wait for IPadr on wlan0
Feb 16 17:17:34 raspberrypi hotspot[374]:   DHCP    wait for IPadr on wlan0
Feb 16 17:17:36 raspberrypi hotspot[374]:   DHCP    wait for IPadr on wlan0
Feb 16 17:17:38 raspberrypi hotspot[374]:   DHCP    wait for IPadr on wlan0
Feb 16 17:17:41 raspberrypi hotspot[374]:   DHCP    wait for IPadr on wlan0 192.168.1.249/24
Feb 16 17:17:42 raspberrypi hotspot:   PARAM   ap_share not set to yes
Feb 16 17:17:42 raspberrypi hotspot[374]: <13>Feb 16 17:17:42 hotspot:   PARAM   ap_share not set to yes
Feb 16 17:17:42 raspberrypi hotspot[374]:   QRcode  show 192.168.1.249
Feb 16 17:17:43 raspberrypi systemd[1]: hotspot.service: Succeeded.
Feb 16 17:17:43 raspberrypi systemd[1]: Started hotspot.
```
but the AP is no exposed. Once I run `hotspot start` work out as expected.
```
root@raspberrypi:~# hotspot start
starting  hotspot V0.960
  ETHER   eth0
  WLANint wlan0   192.168.1.249/24
  WLANext
  UseChan channel 4
  modify  channel strategy: select same channel for ap & station mode on wlan0 4 4
  select  hw_mode g  chan 4
  change  hostapd channel 4 (/etc/hostapd/hostapd.conf)
  change  hostapd hw_mode g (/etc/hostapd/hostapd.conf)
  stop    hostapd
  stop    dnsmasq
  install & check dev ap0
  assign  dev ap0 10.3.141.1/24 on wlan0
  install dev ap0 on wlan0 done
  ipt     wipe ap
  ipt     chains
  ipt     add ap
  ipt     ap   -A wlan0 ap0 10.3.141.0/24
  start   hostapd restart
  start   dnsmasq
started   hotspot
hostapd   active (running)
dnsmasq   active (running)
```

manually adding `hotspot startmode try >>/tmp/hotspot.log 2>&1` to `rc.local` doesn't do anything either. The only thing I then find in the log is this
```
ERR: since V0.960 not needed, started by systemd
```

I guess this is a dependency issue/race condition.
I'd suspect in order to start correctly some other service needs to be running already but isn't.
I also noticed a few seconds after logging in (automatically) some background task throws this message
```
Oops: Terminated
````

**Comment by rudiratlos** [comment]
script don't use this parameter anymore, as documented.
The script >0.960 will automatically started by systemd not by rc.local anymore.
Pls. see /lib/systemd/system/hotspot.service

Just use:
hostspot enable
or
hostspot disable

**Comment by ScruffR** [comment]
Using that parameter was just an attempt to solve the actual problem of the service not starting automatically.

I still have to explicitly call `hotspot start` to get it started despite the fact that the `autostart` parameter is set to `yes` *and* `hotspot enable` being called prior to the reboot.

Hence my assertion still stands
> I'd suspect in order to start correctly some other service needs to be running already but isn't.

BTW, in post 29.12.2020 I took your "suggestion" 
> the required entry in rc.local is:
> `hotspot startmode try >>/tmp/hotspot.log 2>&1`

as: "you can try using the old method too"

**Comment by rudiratlos** [comment]
sorry, I do not have a ZeroW. I can not test if this is race condition. on my rpi4 it's working.

**Comment by hyuei** [comment]
I logged in just to say THANK YOU to @volkerwarnecke !
His  hotspot start >>/tmp/hotspot.log 2>&1 solution helps me regain autostart capability.

I don't know what happened, but here's the thing that happened to me:

- Raspbian Buster 10.8, Raspberry Pi 3 Model B Rev 1.2
- I always ran autostart settings from the beginning. I've used this from 2019, and I've updated the script in around jan-feb
- few months back, I can see sometimes my AP shows up without using any command. But several weeks ago, I disabled autostart since I never leave home, and I guess it's better to save some power?
- today, I tried reenabling it, but it never autostarted. I tried removing and reinstalling hotspot multiple times, but no dice.
- here's the interesting part: I gave up and remember that it was working flawlessly on 2019, so I downloaded hotspot version 0.9.40. **Autostart did not work either!** I guess it worked in 2019 because I'm still in Jessie or something.
- and then, I tried @volkerwarnecke 's solution on 0.9.40, and it worked! autostart working flawlessly.
- since it worked, I tried reverting to the latest hotspot (0.9.60), and autostart didn't work in the beginning, as expected. But by using his solution on rc.local, it now works flawlessly.

(I'm not a programmer, just a hobbyist who copy pasted multiple stuffs from the internet, so maybe this won't be too much help haha)

**Comment by hyuei** [comment]
Update: today I reverted the rc.local to hotspot startmode try, and everything works as expected again (I am still using previous version, so I'm still dependent on rc.local). I guess some sudo apt upgrade that I did these past few weeks has fixed stuff? I'll just try not to update too often if there are no problem, lol.
