### ISSUE TITLE
Make wlan1 the AP and wlan0 the connect

### ISSUE THREAD

**Issue by saulable** [rudiratlos/hotspot#6]
Is it possible to switch the configuration so that we connect to the external card .ie wlan1 becomes ap0? Like maybe set a modpar variable?

The reason being, the pi3 comes with 5GHZ standard and not all network cards have 5GHZ, so it's better to do it the other way, plus they have better range. 

Great work on the script.

**Comment by jsn0327** [comment]
I'm not the developer of the script, but I wanted to do something similar, so I did some research and figured out that the script does not name the interfaces.  By default, the interaces are named based off of when they are loaded on boot up.  On the rPi, you can create a .link file with some matching criteria (i used the MAC address of each interface) to assign the interface names at boot.  More info can be found by reading the man page for systemd.link.

**Comment by rudiratlos** [comment]
swapping ap0 to external wlan-adapter is to complicated/error-prone, 
because hostapd.conf requires a definition for the driver (e.g. driver=rtl871xdrv).
to figure out which driver to use for every available usb-wlan-device is difficult. using the on board device is easy, because the driver is always nl80211
